language: node_js
node_js:
  - "5.3"
  - "4.2"
  - "4.1"
  - "4.0"
sudo: false
before_script:
  - npm install -g gulp
script:
  - npm test
after_script:
  - "test -e ./coverage/lcov/lcov.info && cat ./coverage/lcov//lcov.info | coveralls"
