env:
  global:
      - NODE_ENV=travisci
language: node_js
node_js:
  - "5.3"
  - "4.2"
  - "4.1"
sudo: false
script:
  - npm test
before_script:
  - npm install -g gulp
  - mysql -e 'CREATE DATABASE podslurp_travis_test';
  - gulp db:migrate
after_script:
  - "test -e ./coverage/lcov/lcov.info && cat ./coverage/lcov//lcov.info | coveralls"
services:
  - mysql
